// Generated by CoffeeScript 1.9.3
(function() {
  var controlpage, page, system, webpage;

  system = require('system');

  webpage = require('webpage');

  controlpage = webpage.create();

  page = void 0;

  controlpage.onCallback = function(data) {
    var value;
    switch (data.cmd) {
      case "create":
        page = webpage.create();
        return controlpage.evaluate(function() {
          return window.socket.emit("create");
        });
      case "open":
        if (data.viewportSize) {
          page.viewportSize = data.viewportSize;
        }
        return page.open(data.url, (function(_this) {
          return function(status) {
            return controlpage.evaluate(function(obj) {
              return window.socket.emit("open", obj);
            }, {
              status: status
            });
          };
        })(this));
      case "render":
        page.render(data.patchFile, data.option);
        return controlpage.evaluate(function() {
          return window.socket.emit("render");
        });
      case "evaluate":
        value = page.evaluate(data.vFunction, data.value);
        return controlpage.evaluate(function(obj) {
          return window.socket.emit("evaluate", obj);
        }, value);
      case "paperSize":
        return page.paperSize = data.paperSize;
      case "exit":
        return phantom.exit();
    }
  };

  controlpage.onError = function(msg, trace) {
    return console.log(msg, trace);
  };

  controlpage.open('http://127.0.0.1:' + system.args[1] + '/', function(status) {});

}).call(this);

//# sourceMappingURL=phantomjs.js.map
