// Generated by CoffeeScript 1.9.3
(function() {
  var cNodePhantomjs, nodePhantomjs;

  cNodePhantomjs = require("./node_phantomjs.js");

  nodePhantomjs = new cNodePhantomjs({
    phantomPath: "c:/phantomjs-2.0.0-windows/bin/phantomjs.exe"
  });

  nodePhantomjs.create(function() {
    return nodePhantomjs.open("http://lukomskiy.com.ua/votermark/natgrobnii_plitu-020.jpg", {
      width: 1,
      height: 1
    }, function(status) {
      console.log(status);
      return nodePhantomjs.evaluate(function() {
        var Height, Width;
        document.getElementById('img2').remove();
        Width = document.getElementById('img1').offsetWidth;
        Height = document.getElementById('img1').offsetHeight;
        return {
          width: Width,
          height: Height
        };
      }, function(res) {
        console.log(res);
        return nodePhantomjs.render("test.jpg", function() {
          return nodePhantomjs.stop();
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=test.js.map
